version: '3.6'
services:
  sdk:
    build: .
    container_name: sdk-juridico
    stdin_open: true
    tty: true
    restart: always
    command: npm run dev
    depends_on:
      - mongo-db
    environment:
      PORT: ${PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: 27017
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
      MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}
      WAIT_HOSTS: mongo-db:27017
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      network:

  mongo-db:
    image: mongo:latest
    container_name: mongo-juridico
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
      MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}
    ports:
      - "${MONGO_GLOBAL_PORT}:27017"
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-mongo-script/:/docker-entrypoint-initdb.d
    networks:
      network:

  mongo-seed:
    build: ./dataload
    container_name: juridico-mongo-seed
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
      MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}
      WAIT_HOSTS: mongo-db:27017
    depends_on:
      - mongo-db
      - sdk
    links:
      - mongo-db
      - sdk
    networks:
      network:

volumes:
  node_modules:
  mongodb_data_container:
networks:
  network:
    driver: bridge